# Generated by Django 3.2.5 on 2021-07-05 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.TextField(max_length=1000)),
                ('is_enabled', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(max_length=1000)),
                ('last_name', models.TextField(max_length=1000)),
                ('email', models.EmailField(max_length=254)),
                ('date_of_birth', models.DateField()),
                ('phone_number', models.TextField(max_length=20)),
                ('gender', models.TextField(max_length=20)),
                ('address', models.TextField(max_length=10000)),
                ('state', models.TextField(max_length=1000)),
                ('city', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='client_images/')),
                ('remarks', models.TextField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.TextField(max_length=1000, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subcategory_name', models.TextField(max_length=1000)),
                ('is_enabled', models.BooleanField(default=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.status')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_name', models.TextField(max_length=1000)),
                ('is_enabled', models.BooleanField(default=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.status')),
            ],
        ),
        migrations.CreateModel(
            name='client_service_records',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.category')),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.services')),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.subcategory')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.status'),
        ),
        migrations.AddField(
            model_name='category',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.status'),
        ),
        migrations.AddField(
            model_name='category',
            name='subcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.subcategory'),
        ),
    ]
