# Generated by Django 3.2.5 on 2021-07-30 11:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='state',
        ),
        migrations.AddField(
            model_name='client_service_records',
            name='refered_by',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='client',
            name='emergency_phone_number',
            field=models.TextField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='client_images',
            name='date_of_add',
            field=models.DateField(default=datetime.date(2021, 7, 30)),
        ),
        migrations.AlterField(
            model_name='client_service_records',
            name='date_of_visit',
            field=models.DateField(default=datetime.date(2021, 7, 30)),
        ),
    ]
