# Generated by Django 3.2.5 on 2021-07-06 19:43

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('client', '0002_auto_20210706_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='client',
            name='status',
        ),
        migrations.AddField(
            model_name='client_service_records',
            name='date_of_visit',
            field=models.DateField(default=datetime.date(2021, 7, 7)),
        ),
        migrations.AddField(
            model_name='client_service_records',
            name='remarks',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AddField(
            model_name='client_service_records',
            name='status',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='client.status'),
        ),
        migrations.AlterField(
            model_name='services',
            name='service_name',
            field=models.TextField(max_length=1000, unique=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='subcategory_name',
            field=models.TextField(max_length=1000, unique=True),
        ),
    ]
