# Generated by Django 3.2.5 on 2021-07-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.TextField(max_length=100),
        ),
    ]
