# Generated by Django 3.2.5 on 2021-07-04 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210704_2203'),
    ]

    operations = [
        migrations.CreateModel(
            name='loginDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('otp', models.TextField()),
                ('exp', models.TextField()),
                ('is_active', models.BooleanField()),
            ],
        ),
    ]
